server {
    listen 80 default_server;
    root /app;
    index /public/index.php;

    location / {
        try_files $uri $uri/ /public/index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}